kind: pipeline
name: default

steps:
  - name: ci
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - make ci
      - ls -lrt
  - name: cd
    image: plugins/docker
    volumes:
      - name: deps
        path: /go
    commands:
      - ls -lrt
      - make cd

volumes:
  - name: deps
    temp: {}
