kind: pipeline
type: docker
name: default

steps:
  - name: ci
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - make ci
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: sekulicd/summer_repo
      username: { from_secret: DOCKER_USERNAME }
      password: { from_secret: DOCKER_PASSWORD }
      tags:
        - latest

volumes:
  - name: deps
    temp: {}
