apiVersion: v1
kind: Service
metadata:
  name: summer-service
  labels: { app.kubernetes.io/name: users-grpc }
spec:
  type: NodePort
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
  selector:
    app: summer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: summer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summer
  template:
    metadata:
      labels:
        app: summer
    spec:
      containers:
        - name: summer-app-container
          image: sekulicd/summer_repo:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 50051
