apiVersion: apps/v1
kind: Deployment
metadata:
  name: summer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: summer
  template:
    metadata:
      labels:
        app: summer
    spec:
      containers:
        - name: summer-app-container
          image: sekulicd/summer_repo:dev
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
