// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/grpc-schema/summer.proto

package summer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestTuple struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int32    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestTuple) Reset()         { *m = RequestTuple{} }
func (m *RequestTuple) String() string { return proto.CompactTextString(m) }
func (*RequestTuple) ProtoMessage()    {}
func (*RequestTuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a8da79aebf31a1, []int{0}
}

func (m *RequestTuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestTuple.Unmarshal(m, b)
}
func (m *RequestTuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestTuple.Marshal(b, m, deterministic)
}
func (m *RequestTuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestTuple.Merge(m, src)
}
func (m *RequestTuple) XXX_Size() int {
	return xxx_messageInfo_RequestTuple.Size(m)
}
func (m *RequestTuple) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestTuple.DiscardUnknown(m)
}

var xxx_messageInfo_RequestTuple proto.InternalMessageInfo

func (m *RequestTuple) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *RequestTuple) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type RequestTriple struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int32    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	C                    int32    `protobuf:"varint,3,opt,name=c,proto3" json:"c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestTriple) Reset()         { *m = RequestTriple{} }
func (m *RequestTriple) String() string { return proto.CompactTextString(m) }
func (*RequestTriple) ProtoMessage()    {}
func (*RequestTriple) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a8da79aebf31a1, []int{1}
}

func (m *RequestTriple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestTriple.Unmarshal(m, b)
}
func (m *RequestTriple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestTriple.Marshal(b, m, deterministic)
}
func (m *RequestTriple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestTriple.Merge(m, src)
}
func (m *RequestTriple) XXX_Size() int {
	return xxx_messageInfo_RequestTriple.Size(m)
}
func (m *RequestTriple) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestTriple.DiscardUnknown(m)
}

var xxx_messageInfo_RequestTriple proto.InternalMessageInfo

func (m *RequestTriple) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *RequestTriple) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

func (m *RequestTriple) GetC() int32 {
	if m != nil {
		return m.C
	}
	return 0
}

type Response struct {
	Sum                  int32    `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_46a8da79aebf31a1, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSum() int32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestTuple)(nil), "summer.RequestTuple")
	proto.RegisterType((*RequestTriple)(nil), "summer.RequestTriple")
	proto.RegisterType((*Response)(nil), "summer.Response")
}

func init() { proto.RegisterFile("pkg/grpc-schema/summer.proto", fileDescriptor_46a8da79aebf31a1) }

var fileDescriptor_46a8da79aebf31a1 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x29, 0xc8, 0x4e, 0xd7,
	0x4f, 0x2f, 0x2a, 0x48, 0xd6, 0x2d, 0x4e, 0xce, 0x48, 0xcd, 0x4d, 0xd4, 0x2f, 0x2e, 0xcd, 0xcd,
	0x4d, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xb4, 0xb8, 0x78,
	0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x42, 0x4a, 0x0b, 0x72, 0x52, 0x85, 0x78, 0xb8, 0x18,
	0x13, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x18, 0x13, 0x41, 0xbc, 0x24, 0x09, 0x26, 0x08,
	0x2f, 0x49, 0xc9, 0x92, 0x8b, 0x17, 0xa6, 0xb6, 0x28, 0x93, 0x80, 0x62, 0x10, 0x2f, 0x59, 0x82,
	0x19, 0xc2, 0x4b, 0x56, 0x92, 0xe1, 0xe2, 0x08, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15,
	0x12, 0xe0, 0x62, 0x2e, 0x2e, 0xcd, 0x85, 0xea, 0x03, 0x31, 0x8d, 0x8a, 0xb8, 0xd8, 0x82, 0xc1,
	0xce, 0x11, 0x32, 0xe2, 0xe2, 0x48, 0x4c, 0x49, 0x81, 0x38, 0x45, 0x44, 0x0f, 0xea, 0x62, 0x64,
	0x07, 0x4a, 0x09, 0x20, 0x44, 0xa1, 0xe6, 0x99, 0x70, 0x71, 0x82, 0xf4, 0x40, 0x9c, 0x24, 0x8a,
	0xae, 0x09, 0x2c, 0x8c, 0xa9, 0x2b, 0x89, 0x0d, 0x1c, 0x0e, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x77, 0xab, 0x01, 0x7c, 0x27, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SummerClient is the client API for Summer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SummerClient interface {
	AddTuple(ctx context.Context, in *RequestTuple, opts ...grpc.CallOption) (*Response, error)
	AddTriple(ctx context.Context, in *RequestTriple, opts ...grpc.CallOption) (*Response, error)
}

type summerClient struct {
	cc *grpc.ClientConn
}

func NewSummerClient(cc *grpc.ClientConn) SummerClient {
	return &summerClient{cc}
}

func (c *summerClient) AddTuple(ctx context.Context, in *RequestTuple, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/summer.Summer/addTuple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *summerClient) AddTriple(ctx context.Context, in *RequestTriple, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/summer.Summer/addTriple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SummerServer is the server API for Summer service.
type SummerServer interface {
	AddTuple(context.Context, *RequestTuple) (*Response, error)
	AddTriple(context.Context, *RequestTriple) (*Response, error)
}

// UnimplementedSummerServer can be embedded to have forward compatible implementations.
type UnimplementedSummerServer struct {
}

func (*UnimplementedSummerServer) AddTuple(ctx context.Context, req *RequestTuple) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTuple not implemented")
}
func (*UnimplementedSummerServer) AddTriple(ctx context.Context, req *RequestTriple) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTriple not implemented")
}

func RegisterSummerServer(s *grpc.Server, srv SummerServer) {
	s.RegisterService(&_Summer_serviceDesc, srv)
}

func _Summer_AddTuple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTuple)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummerServer).AddTuple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/summer.Summer/AddTuple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummerServer).AddTuple(ctx, req.(*RequestTuple))
	}
	return interceptor(ctx, in, info, handler)
}

func _Summer_AddTriple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTriple)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SummerServer).AddTriple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/summer.Summer/AddTriple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SummerServer).AddTriple(ctx, req.(*RequestTriple))
	}
	return interceptor(ctx, in, info, handler)
}

var _Summer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "summer.Summer",
	HandlerType: (*SummerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addTuple",
			Handler:    _Summer_AddTuple_Handler,
		},
		{
			MethodName: "addTriple",
			Handler:    _Summer_AddTriple_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc-schema/summer.proto",
}
